modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "farmies"
version = "${version}"
displayName = "Farmies"
authors = "LunazStudios"
description = '''
Turn your Minecraft world into a thriving farm with Farmies!
'''
logoFile = "icon.png"

[[dependencies.farmies]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.farmies]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.farmies]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "farmies.mixins.json"
